# action.yml
name: 'Combine witness signatures'
description: 'Serverless witness distributor: combine witness signatures'
inputs:
  distributor_dir:
    description: 'Location of the distributor files in the repo'
    required: true
    default: 'distributor'
  config:
    description: 'Path to the config file in JSON format'
    required: true
  dry_run:
    description: 'Do not write or modify any files'
    default: false
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'loader'
  color: 'orange'
