Log:
  Origin: ArmoryDrive Log v0
  PublicKey: armory-drive-log-test+a5aae457+AbDoiIsZgSk5H0v0LjKPKv5dAMb0IfB47tocFtGmyW44
  URL: https://raw.githubusercontent.com/f-secure-foundry/armory-drive-log/master/log/

Witness:
  URL: http://localhost:8765
  PublicKey: test-witness+d28ecb0d+AV2DM8GnnoXPS77FKY/KwsZdfien9eSmb35f6qUv2TrH
