Logs:
  - Origin: rekor.sigstore.dev - 3904496407287907110
    PublicKeyType: ecdsa
    PublicKey: rekor.sigstore.dev+c0d23d6a+AjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNhtmPtrWm3U1eQXBogSMdGvXwBcK5AW5i0hrZLOC96l+smGNM7nwZ4QvFK/4sueRoVj//QP22Ni4Qt9DPfkWLc=
    URL: https://rekor.sigstore.dev?treeID=3904496407287907110
  - Origin: rekor.sigstore.dev - 2605736670972794746
    PublicKeyType: ecdsa
    PublicKey: rekor.sigstore.dev+c0d23d6a+AjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNhtmPtrWm3U1eQXBogSMdGvXwBcK5AW5i0hrZLOC96l+smGNM7nwZ4QvFK/4sueRoVj//QP22Ni4Qt9DPfkWLc=
    URL: https://rekor.sigstore.dev?treeID=2605736670972794746

Witness:
  URL: http://localhost:8100