version: '3.2'
services:
  witness:
    build:
      context: ../../../..
      dockerfile: ./witness/golang/cmd/witness/Dockerfile
    volumes:
        - type: volume
          source: data
          target: /data
          volume:
            nocopy: true
        - type: bind
          source: ${WITNESS_CONFIG_DIR:-/etc/witness/config}
          target: /witness-config
          read_only: true
    command:
      - "--listen=:8100"
      - "--db_file=/data/witness.sqlite"
      - "--private_key=${WITNESS_PRIVATE_KEY}"
      - "--config_file=/witness-config/${WITNESS_CONFIG_FILE:-witness.config}"
      - "--logtostderr"
    restart: always
    expose:
      - "8100"
  feeder:
    depends_on:
      - witness
    build:
      context: ../../../..
      dockerfile: ./serverless/cmd/feeder/Dockerfile
    command:
      - "--config_file=/feeder-config/${FEEDER_DISTRIBUTOR_CONFIG_FILE:-feeder.config}"
      - "--interval=${INTERVAL_SECONDS:-300}"
      - "--logtostderr"
    restart: always
    volumes:
      - type: bind
        source: ${FEEDER_DISTRIBUTOR_CONFIG_DIR:-/etc/feeder/config}
        target: /feeder-config
  distributor:
    depends_on:
      - witness
    build:
      context: ../../../..
      dockerfile: ./serverless/cmd/distribute/github/Dockerfile
    command:
      - "--config_file=/distributor-config/${FEEDER_DISTRIBUTOR_CONFIG_FILE:-feeder.config}"
      - "--distributor_repo=${SERVERLESS_DISTRIBUTOR_REPO}"
      - "--fork_repo=${SERVERLESS_DISTRIBUTOR_FORK}"
      - "--distributor_path=${SERVERLESS_DISTRIBUTOR_DIR:-.}"
      - "--interval=${INTERVAL_SECONDS:-300}"
      - "--clone_to_disk=${CLONE_TO_DISK:-false}"
      - "--logtostderr"
    environment:
      - GITHUB_AUTH_TOKEN=${DISTRIBUTOR_GITHUB_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_EMAIL=${GIT_EMAIL}
    restart: always
    volumes:
      - type: bind
        source: ${FEEDER_DISTRIBUTOR_CONFIG_DIR:-/etc/feeder/config}
        target: /distributor-config
      - type: tmpfs
        target: /tmp
volumes:
  data:

